### PR TITLE
DYN-5219-Dismiss-feature-notification-icon-should-mark-as-read

### PR DESCRIPTION
**Pull request by Enzo707**
This PR implements a solution for [DYN-5219](https://jira.autodesk.com/browse/DYN-5219)
Now, anytime we dismiss a notification it will be mark as read and will be removed from the list.

DYN-5219

**FYI**
@QilongTang 
@RobertGlobant20

### CODE REVIEW

**Comment by reddyashish** [comment]
so how do we remove a notification from the panel? I feel it is confusing that the notification is not hidden or something when you click 'X'

**Comment by QilongTang** [comment]
Agreed. I think clicking - dismiss itself should still happen, so I expect with each click the notification disappear and also be marked as read

**Comment by Enzo707** [comment]
@reddyashish @QilongTang I've just sticked to the ticket's description but yes, it's kinda confusing. I could remove the notification item from the list when it's marked as read. Just let me know

**Comment by QilongTang** [comment]
> @reddyashish @QilongTang I've just sticked to the ticket's description but yes, it's kinda confusing. I could remove the notification item from the list when it's marked as read. Just let me know

Please do and I will update the Jira ticket tomorrow

**Review by reddyashish — APPROVED** [review]

**Comment by QilongTang** [comment]
@Enzo707 Can you update the PR description? Would you log gifs in the future instead of videos?

**Comment by Enzo707** [comment]
> @Enzo707 Can you update the PR description? Would you log gifs in the future instead of videos?

@QilongTang I've already updated the PR description and replaced the video with a .gif

**Review by QilongTang — APPROVED** [review]

**Comment by QilongTang** [comment]
Hi @Enzo707 Please publish and update other repos thanks!

**Comment by Enzo707** [comment]
> Hi @Enzo707 Please publish and update other repos thanks!

@QilongTang I have to publish Notification-panel package only? 
If I'm not wrong we already have github actions for publishing NotificationCenter, right?

**Comment by QilongTang** [comment]
Yes @Enzo707 You only need to publish the package for this repo, and then make PRs in the consumer repo for version updates

**Pull request merged**
